AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(10 minutes)"
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt LambdaFunction.Arn
          Id: "TargetFunctionV1"
