version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/*"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/perf"
    schedule:
      interval: "daily"