export enum SpanKeynameEnum {
    ChildContainerCreation = "child.container.creation",
    ConfigurationInitialization = "configuration.initialization",
    ErrorResponseInterceptors = "error.response.interceptors",
    EventExecution = "event.execution",
    EventInitialization = "event.initialization",
    KernelInitialization = "kernel.initialization",
    ModuleInitialization = "module.initialization",
    ModuleInitializationImportModules = "module.initialization.import.modules",
    RequestExecution = "request.execution",
    RequestInterceptors = "request.interceptors",
    ResponseInterceptors = "response.interceptors",
    RootExecution = "root.execution",
    RouterControllerResolver = "router.controller.resolver",
    RouterFindMethodRouterNode = "router.find.method.router.node",
    RouterRequestAuthentication = "router.request.authentication",
    RouterRequestEnrichers = "router.request.enrichers",
    RouterRequestExecution = "router.request.execution",
    RouterResponseEnrichers = "router.response.enrichers",
    RouterSetup = "router.setup",
}
