#!/usr/bin/env node
// Writes the CLI's own version from package.json into src/generated/version.ts as a plain
// compile-time constant, the value `pristine info` prints. A constant works identically in
// CommonJS, native ESM, and bundled ESM: it needs no filesystem read, no `__dirname`, and no
// `import.meta`, so it still resolves after a consumer bundles the CLI away from its package.json
// (where a runtime package.json lookup cannot find the version and `__dirname` may not exist).
//
// Runs on `prebuild` and `pretest` so the constant is present and current before tsc or ts-jest
// compiles the code that imports it.

import {readFileSync, writeFileSync, mkdirSync} from "node:fs";
import {fileURLToPath} from "node:url";
import {dirname, resolve} from "node:path";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDir, "..");

const pkg = JSON.parse(readFileSync(resolve(packageRoot, "package.json"), "utf8"));
const version = typeof pkg.version === "string" && pkg.version.length > 0 ? pkg.version : "unknown";

const generatedDir = resolve(packageRoot, "src", "generated");
mkdirSync(generatedDir, {recursive: true});

const contents = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.
// Regenerated from package.json on every \`npm run build\` and \`npm test\` (prebuild/pretest).
// Annotated \`: string\` (not the inferred literal type) so callers can treat it as an ordinary
// version string — e.g. compare it against other strings — without TypeScript narrowing it to the
// single baked-in value.
export const CLI_VERSION: string = ${JSON.stringify(version)};
`;

writeFileSync(resolve(generatedDir, "version.ts"), contents);

console.log(`generated src/generated/version.ts (CLI_VERSION="${version}")`);
