#!/usr/bin/env node
// Writes the CLI's own version from package.json into src/generated/version.ts as a plain
// compile-time constant. This is the PRIMARY source `pristine info` reads for its version — it
// works identically in CommonJS, native ESM, and bundled ESM because it needs no filesystem read,
// no `__dirname`, and no `import.meta`. (Runtime path resolution can't recover the version once a
// consumer bundles the CLI away from its package.json — see CliPackageJsonResolver.)
//
// Runs on both `prebuild` and `pretest` so the constant is always present and fresh before tsc
// or ts-jest compiles the resolver that imports it.

import {readFileSync, writeFileSync, mkdirSync} from "node:fs";
import {fileURLToPath} from "node:url";
import {dirname, resolve} from "node:path";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDir, "..");

const pkg = JSON.parse(readFileSync(resolve(packageRoot, "package.json"), "utf8"));
const version = typeof pkg.version === "string" && pkg.version.length > 0 ? pkg.version : "unknown";

const generatedDir = resolve(packageRoot, "src", "generated");
mkdirSync(generatedDir, {recursive: true});

const contents = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.
// Regenerated from package.json on every \`npm run build\` and \`npm test\` (prebuild/pretest).
// This is the primary, bundle-safe source of the CLI version: no filesystem read, no __dirname,
// no import.meta — so it resolves correctly in CommonJS, native ESM, and bundled ESM alike.
// Annotated \`: string\` (not the literal type) so the resolver's runtime guards against a
// missing/blank value are legal comparisons rather than TS "no overlap" errors.
export const CLI_VERSION: string = ${JSON.stringify(version)};
`;

writeFileSync(resolve(generatedDir, "version.ts"), contents);

console.log(`generated src/generated/version.ts (CLI_VERSION="${version}")`);
